name: "Publish Docker image to GHCR"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare image names (lowercase + sanitize)
        id: vars
        run: |
          # Get owner and repo from environment
          owner="${GITHUB_REPOSITORY_OWNER}"
          # GITHUB_REPOSITORY is owner/repo, strip owner/
          repo="${GITHUB_REPOSITORY#*/}"

          # Lowercase
          owner_lc="$(printf '%s' "$owner" | tr '[:upper:]' '[:lower:]')"
          repo_lc="$(printf '%s' "$repo"  | tr '[:upper:]' '[:lower:]')"

          # Derive a safe tag from the ref (e.g., refs/heads/feature/foo -> feature-foo)
          ref="${GITHUB_REF#refs/heads/}"      # for branch builds
          # fallback to short SHA if ref is empty
          if [ -z "$ref" ]; then
            ref="${GITHUB_SHA::7}"
          fi
          # sanitize: lowercase, replace '/' and spaces with '-'
          tag="$(printf '%s' "$ref" | tr '[:upper:]' '[:lower:]' | sed -E 's#[/: ]+#-#g')"

          echo "owner=${owner_lc}" >> "$GITHUB_OUTPUT"
          echo "repo=${repo_lc}" >> "$GITHUB_OUTPUT"
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: >
            ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.repo }}:latest,
            ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.tag }},
            ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.repo }}:${{ github.sha }}
